networks:
  scoobydoo:
    external: true

services:
  tg-signer-yl:
    ports:
      - "127.0.0.1:8119:8119"
    build:
      context: .
      dockerfile: ./docker/Run.Dockerfile
      args:
        TZ: ${TZ:-Asia/Shanghai}
    container_name: tg-signer-yl
    # command: ["webgui", "--host", "0.0.0.0", "--port", "8119"]
    command: ["run", "nebula", "-n", "1000"]
    volumes:
      - ./data:/app
    environment:
    #   - TG_PROXY=socks5://172.17.0.1:7890
      - TZ=${TZ:-Asia/Shanghai}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
      - BARK_URL=${BARK_URL:-}
      - BARK_SOUND=${BARK_SOUND:-}
      - BARK_GROUP=${BARK_GROUP:-}
    networks:
      - scoobydoo
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
